% -------------------------------------------------------------------
%  Generated by MATLAB on 5-May-2023 12:24:43
%  MATLAB version: 9.12.0.2009381 (R2022a) Update 4
% -------------------------------------------------------------------
                                     

param_ABSampslimit_hyst_A = Simulink.Parameter;
param_ABSampslimit_hyst_A.Value = 25;
param_ABSampslimit_hyst_A.Complexity = 'real';
param_ABSampslimit_hyst_A.HasCoderInfo = false;
param_ABSampslimit_hyst_A.Description = '';
param_ABSampslimit_hyst_A.DataType = 'int16';
param_ABSampslimit_hyst_A.Min = 0;
param_ABSampslimit_hyst_A.Max = 25;
param_ABSampslimit_hyst_A.DocUnits = 'A';

param_Dchg_10sPL_expiry_dur_thresh_ms = Simulink.Parameter;
param_Dchg_10sPL_expiry_dur_thresh_ms.Value = 10000;
param_Dchg_10sPL_expiry_dur_thresh_ms.Complexity = 'real';
param_Dchg_10sPL_expiry_dur_thresh_ms.HasCoderInfo = false;
param_Dchg_10sPL_expiry_dur_thresh_ms.Description = '';
param_Dchg_10sPL_expiry_dur_thresh_ms.DataType = 'uint32';
param_Dchg_10sPL_expiry_dur_thresh_ms.Min = 0;
param_Dchg_10sPL_expiry_dur_thresh_ms.Max = 65500;
param_Dchg_10sPL_expiry_dur_thresh_ms.DocUnits = 'msec';

param_Dchg_50sPL_expiry_dur_thresh_ms = Simulink.Parameter;
param_Dchg_50sPL_expiry_dur_thresh_ms.Value = 50000;
param_Dchg_50sPL_expiry_dur_thresh_ms.Complexity = 'real';
param_Dchg_50sPL_expiry_dur_thresh_ms.HasCoderInfo = false;
param_Dchg_50sPL_expiry_dur_thresh_ms.Description = '';
param_Dchg_50sPL_expiry_dur_thresh_ms.DataType = 'uint32';
param_Dchg_50sPL_expiry_dur_thresh_ms.Min = 0;
param_Dchg_50sPL_expiry_dur_thresh_ms.Max = 65500;
param_Dchg_50sPL_expiry_dur_thresh_ms.DocUnits = 'msec';

param_Regen_10sPL_expiry_dur_thresh_ms = Simulink.Parameter;
param_Regen_10sPL_expiry_dur_thresh_ms.Value = 10000;
param_Regen_10sPL_expiry_dur_thresh_ms.Complexity = 'real';
param_Regen_10sPL_expiry_dur_thresh_ms.HasCoderInfo = false;
param_Regen_10sPL_expiry_dur_thresh_ms.Description = '';
param_Regen_10sPL_expiry_dur_thresh_ms.DataType = 'uint32';
param_Regen_10sPL_expiry_dur_thresh_ms.Min = 0;
param_Regen_10sPL_expiry_dur_thresh_ms.Max = 65500;
param_Regen_10sPL_expiry_dur_thresh_ms.DocUnits = 'msec';

param_Regen_50sPL_expiry_dur_thresh_ms = Simulink.Parameter;
param_Regen_50sPL_expiry_dur_thresh_ms.Value = 50000;
param_Regen_50sPL_expiry_dur_thresh_ms.Complexity = 'real';
param_Regen_50sPL_expiry_dur_thresh_ms.HasCoderInfo = false;
param_Regen_50sPL_expiry_dur_thresh_ms.Description = '';
param_Regen_50sPL_expiry_dur_thresh_ms.DataType = 'uint32';
param_Regen_50sPL_expiry_dur_thresh_ms.Min = 0;
param_Regen_50sPL_expiry_dur_thresh_ms.Max = 65500;
param_Regen_50sPL_expiry_dur_thresh_ms.DocUnits = 'msec';

param_cell_heat2cool_factor = Simulink.Parameter;
param_cell_heat2cool_factor.Value = 2;
param_cell_heat2cool_factor.Complexity = 'real';
param_cell_heat2cool_factor.HasCoderInfo = false;
param_cell_heat2cool_factor.Description = '';
param_cell_heat2cool_factor.DataType = 'uint32';
param_cell_heat2cool_factor.Min = 1;
param_cell_heat2cool_factor.Max = 5;
param_cell_heat2cool_factor.DocUnits = '';

table_ABSampslimit_thresh_A = Simulink.LookupTable;
table_ABSampslimit_thresh_A.Table.DataType = 'int16';
table_ABSampslimit_thresh_A.Table.Min = 0;
table_ABSampslimit_thresh_A.Table.Max = 157;
table_ABSampslimit_thresh_A.Table.Unit = 'A';
table_ABSampslimit_thresh_A.Table.FieldName = ...
  'cal_table_vals_abs_ampslimit_thresh_A';
table_ABSampslimit_thresh_A.Table.Description = '';
table_ABSampslimit_thresh_A.Table.Value = int16( ...
  [52; 157; 157; 157; 157; 157; 157; 157; 157; 157; 0]);
table_ABSampslimit_thresh_A.BreakpointsSpecification = ...
  'Explicit values';
table_ABSampslimit_thresh_A.SupportTunableSize = false;
table_ABSampslimit_thresh_A.Breakpoints.DataType = 'int16';
table_ABSampslimit_thresh_A.Breakpoints.Min = -4000;
table_ABSampslimit_thresh_A.Breakpoints.Max = 8000;
table_ABSampslimit_thresh_A.Breakpoints.Unit = 'degC';
table_ABSampslimit_thresh_A.Breakpoints.FieldName = ...
  'cal_table_bkpts_abs_ampslimit_cell_temps_degC';
table_ABSampslimit_thresh_A.Breakpoints.Description = ...
  'units are 1e2 * degC';
table_ABSampslimit_thresh_A.Breakpoints.Value = int16( ...
  [-2000; 0; 1000; 1500; 2500; 3000; 4500; 5000; 5500; 6500; 7000]);
table_ABSampslimit_thresh_A.Breakpoints.TunableSizeName = 'N1';
table_ABSampslimit_thresh_A.HasCoderInfo = false;
table_ABSampslimit_thresh_A.StructTypeInfo.Name = ...
  'ABSampslimit_thresh_A';
table_ABSampslimit_thresh_A.StructTypeInfo.DataScope = 'Auto';
table_ABSampslimit_thresh_A.StructTypeInfo.HeaderFileName = '';

table_Dchg_10sPL = Simulink.LookupTable;
table_Dchg_10sPL.Table.DataType = 'int16';
table_Dchg_10sPL.Table.Min = 0;
table_Dchg_10sPL.Table.Max = 200;
table_Dchg_10sPL.Table.Unit = 'A';
table_Dchg_10sPL.Table.FieldName = ['cal_table_Dchg_10sPL_limits_xtempy' ...
                                    'soc'];
table_Dchg_10sPL.Table.Description = '';
table_Dchg_10sPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 52 105 105 105 105 105 105 105 105 105;
   0 105 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 200 200 200 200 200 200 200 200 200 200;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Dchg_10sPL.BreakpointsSpecification = 'Explicit values';
table_Dchg_10sPL.SupportTunableSize = false;
table_Dchg_10sPL.Breakpoints.DataType = 'uint8';
table_Dchg_10sPL.Breakpoints.Min = 0;
table_Dchg_10sPL.Breakpoints.Max = 100;
table_Dchg_10sPL.Breakpoints.Unit = '%';
table_Dchg_10sPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Dchg_10sPL.Breakpoints.Description = '';
table_Dchg_10sPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Dchg_10sPL.Breakpoints.TunableSizeName = 'N1';
table_Dchg_10sPL.Breakpoints(2).DataType = 'int16';
table_Dchg_10sPL.Breakpoints(2).Min = -4000;
table_Dchg_10sPL.Breakpoints(2).Max = 8000;
table_Dchg_10sPL.Breakpoints(2).Unit = 'degC';
table_Dchg_10sPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Dchg_10sPL.Breakpoints(2).Description = '1e2 * degC';
table_Dchg_10sPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Dchg_10sPL.Breakpoints(2).TunableSizeName = 'N2';
table_Dchg_10sPL.HasCoderInfo = false;
table_Dchg_10sPL.StructTypeInfo.Name = 'Dchg_10sPL';
table_Dchg_10sPL.StructTypeInfo.DataScope = 'Auto';
table_Dchg_10sPL.StructTypeInfo.HeaderFileName = '';

table_Dchg_50sPL = Simulink.LookupTable;
table_Dchg_50sPL.Table.DataType = 'int16';
table_Dchg_50sPL.Table.Min = 0;
table_Dchg_50sPL.Table.Max = 200;
table_Dchg_50sPL.Table.Unit = 'A';
table_Dchg_50sPL.Table.FieldName = ['cal_table_Dchg_50sPL_limits_xtempy' ...
                                    'soc'];
table_Dchg_50sPL.Table.Description = '';
table_Dchg_50sPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 26 52 52 52 52 52 52 52 52 52;
   0 52 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 157 157 157 157 157 157 157 157 157 157;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Dchg_50sPL.BreakpointsSpecification = 'Explicit values';
table_Dchg_50sPL.SupportTunableSize = false;
table_Dchg_50sPL.Breakpoints.DataType = 'uint8';
table_Dchg_50sPL.Breakpoints.Min = 0;
table_Dchg_50sPL.Breakpoints.Max = 100;
table_Dchg_50sPL.Breakpoints.Unit = '%';
table_Dchg_50sPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Dchg_50sPL.Breakpoints.Description = '';
table_Dchg_50sPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Dchg_50sPL.Breakpoints.TunableSizeName = 'N1';
table_Dchg_50sPL.Breakpoints(2).DataType = 'int16';
table_Dchg_50sPL.Breakpoints(2).Min = -4000;
table_Dchg_50sPL.Breakpoints(2).Max = 8000;
table_Dchg_50sPL.Breakpoints(2).Unit = 'degC';
table_Dchg_50sPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Dchg_50sPL.Breakpoints(2).Description = '1e2 * degC';
table_Dchg_50sPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Dchg_50sPL.Breakpoints(2).TunableSizeName = 'N2';
table_Dchg_50sPL.HasCoderInfo = false;
table_Dchg_50sPL.StructTypeInfo.Name = 'Dchg_50sPL';
table_Dchg_50sPL.StructTypeInfo.DataScope = 'Auto';
table_Dchg_50sPL.StructTypeInfo.HeaderFileName = '';

table_Dchg_contPL = Simulink.LookupTable;
table_Dchg_contPL.Table.DataType = 'int16';
table_Dchg_contPL.Table.Min = 0;
table_Dchg_contPL.Table.Max = 200;
table_Dchg_contPL.Table.Unit = 'A';
table_Dchg_contPL.Table.FieldName = ...
  'cal_table_Dchg_contPL_limits_xtempysoc';
table_Dchg_contPL.Table.Description = '';
table_Dchg_contPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 14 14 14 29 29 29 29 29 29 29;
   0 29 29 29 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 58 100 100 100 100 100 100 100 100 100;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Dchg_contPL.BreakpointsSpecification = 'Explicit values';
table_Dchg_contPL.SupportTunableSize = false;
table_Dchg_contPL.Breakpoints.DataType = 'uint8';
table_Dchg_contPL.Breakpoints.Min = 0;
table_Dchg_contPL.Breakpoints.Max = 100;
table_Dchg_contPL.Breakpoints.Unit = '%';
table_Dchg_contPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Dchg_contPL.Breakpoints.Description = '';
table_Dchg_contPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Dchg_contPL.Breakpoints.TunableSizeName = 'N1';
table_Dchg_contPL.Breakpoints(2).DataType = 'int16';
table_Dchg_contPL.Breakpoints(2).Min = -4000;
table_Dchg_contPL.Breakpoints(2).Max = 8000;
table_Dchg_contPL.Breakpoints(2).Unit = 'degC';
table_Dchg_contPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Dchg_contPL.Breakpoints(2).Description = '1e2* degC';
table_Dchg_contPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Dchg_contPL.Breakpoints(2).TunableSizeName = 'N2';
table_Dchg_contPL.HasCoderInfo = false;
table_Dchg_contPL.StructTypeInfo.Name = 'Dchg_contPL';
table_Dchg_contPL.StructTypeInfo.DataScope = 'Auto';
table_Dchg_contPL.StructTypeInfo.HeaderFileName = '';

table_Regen_10sPL = Simulink.LookupTable;
table_Regen_10sPL.Table.DataType = 'int16';
table_Regen_10sPL.Table.Min = 0;
table_Regen_10sPL.Table.Max = 200;
table_Regen_10sPL.Table.Unit = 'A';
table_Regen_10sPL.Table.FieldName = ...
  'cal_table_Regen_10sPL_limits_xtempysoc';
table_Regen_10sPL.Table.Description = '';
table_Regen_10sPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0;
   50 58 58 58 58 58 58 58 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 58 0;
   58 84 84 84 84 84 84 84 58 0 0;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Regen_10sPL.BreakpointsSpecification = 'Explicit values';
table_Regen_10sPL.SupportTunableSize = false;
table_Regen_10sPL.Breakpoints.DataType = 'uint8';
table_Regen_10sPL.Breakpoints.Min = 0;
table_Regen_10sPL.Breakpoints.Max = 100;
table_Regen_10sPL.Breakpoints.Unit = '%';
table_Regen_10sPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Regen_10sPL.Breakpoints.Description = '';
table_Regen_10sPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Regen_10sPL.Breakpoints.TunableSizeName = 'N1';
table_Regen_10sPL.Breakpoints(2).DataType = 'int16';
table_Regen_10sPL.Breakpoints(2).Min = -4000;
table_Regen_10sPL.Breakpoints(2).Max = 8000;
table_Regen_10sPL.Breakpoints(2).Unit = 'degC';
table_Regen_10sPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Regen_10sPL.Breakpoints(2).Description = '1e2 * degC';
table_Regen_10sPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Regen_10sPL.Breakpoints(2).TunableSizeName = 'N2';
table_Regen_10sPL.HasCoderInfo = false;
table_Regen_10sPL.StructTypeInfo.Name = 'Regen_10sPL';
table_Regen_10sPL.StructTypeInfo.DataScope = 'Auto';
table_Regen_10sPL.StructTypeInfo.HeaderFileName = '';

table_Regen_50sPL = Simulink.LookupTable;
table_Regen_50sPL.Table.DataType = 'int16';
table_Regen_50sPL.Table.Min = 0;
table_Regen_50sPL.Table.Max = 150;
table_Regen_50sPL.Table.Unit = 'A';
table_Regen_50sPL.Table.FieldName = ...
  'cal_table_Regen_50sPL_limits_xtempysoc';
table_Regen_50sPL.Table.Description = '';
table_Regen_50sPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0;
   29 29 29 29 29 29 29 29 29 29 0;
   58 58 58 58 58 58 58 58 29 29 0;
   58 58 58 58 58 58 58 58 29 29 0;
   58 58 58 58 58 58 58 58 29 29 0;
   58 58 58 58 58 58 58 58 29 29 0;
   58 58 58 58 58 58 58 58 29 29 0;
   0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Regen_50sPL.BreakpointsSpecification = 'Explicit values';
table_Regen_50sPL.SupportTunableSize = false;
table_Regen_50sPL.Breakpoints.DataType = 'uint8';
table_Regen_50sPL.Breakpoints.Min = 0;
table_Regen_50sPL.Breakpoints.Max = 100;
table_Regen_50sPL.Breakpoints.Unit = '%';
table_Regen_50sPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Regen_50sPL.Breakpoints.Description = '';
table_Regen_50sPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Regen_50sPL.Breakpoints.TunableSizeName = 'N1';
table_Regen_50sPL.Breakpoints(2).DataType = 'int16';
table_Regen_50sPL.Breakpoints(2).Min = -4000;
table_Regen_50sPL.Breakpoints(2).Max = 8000;
table_Regen_50sPL.Breakpoints(2).Unit = 'degC';
table_Regen_50sPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Regen_50sPL.Breakpoints(2).Description = '1e2 * degC';
table_Regen_50sPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Regen_50sPL.Breakpoints(2).TunableSizeName = 'N2';
table_Regen_50sPL.HasCoderInfo = false;
table_Regen_50sPL.StructTypeInfo.Name = 'Regen_50sPL';
table_Regen_50sPL.StructTypeInfo.DataScope = 'Auto';
table_Regen_50sPL.StructTypeInfo.HeaderFileName = '';

table_Regen_contPL = Simulink.LookupTable;
table_Regen_contPL.Table.DataType = 'int16';
table_Regen_contPL.Table.Min = 0;
table_Regen_contPL.Table.Max = 100;
table_Regen_contPL.Table.Unit = 'A';
table_Regen_contPL.Table.FieldName = ...
  'cal_table_Regen_contPL_limits_xtempysoc';
table_Regen_contPL.Table.Description = '';
table_Regen_contPL.Table.Value = int16( ...
  [0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0;
   14 14 14 14 14 14 14 14 14 14 0;
   29 29 29 29 29 29 29 29 14 14 0;
   29 29 29 29 29 29 29 29 14 14 0;
   29 29 29 29 29 29 29 29 14 14 0;
   29 29 29 29 29 29 29 29 14 14 0;
   29 29 29 29 29 29 29 29 14 14 0;
   0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0;
   0 0 0 0 0 0 0 0 0 0 0]);
table_Regen_contPL.BreakpointsSpecification = 'Explicit values';
table_Regen_contPL.SupportTunableSize = false;
table_Regen_contPL.Breakpoints.DataType = 'uint8';
table_Regen_contPL.Breakpoints.Min = 0;
table_Regen_contPL.Breakpoints.Max = 100;
table_Regen_contPL.Breakpoints.Unit = '%';
table_Regen_contPL.Breakpoints.FieldName = ...
  'cal_table_bkpts_cell_soc_percent';
table_Regen_contPL.Breakpoints.Description = '';
table_Regen_contPL.Breakpoints.Value = uint8( ...
  [0; 10; 20; 30; 40; 60; 70; 80; 90; 95; 100]);
table_Regen_contPL.Breakpoints.TunableSizeName = 'N1';
table_Regen_contPL.Breakpoints(2).DataType = 'int16';
table_Regen_contPL.Breakpoints(2).Min = -4000;
table_Regen_contPL.Breakpoints(2).Max = 8000;
table_Regen_contPL.Breakpoints(2).Unit = 'degC';
table_Regen_contPL.Breakpoints(2).FieldName = ...
  'cal_table_bkpts_cell_temp_degC';
table_Regen_contPL.Breakpoints(2).Description = '1e2 * degC';
table_Regen_contPL.Breakpoints(2).Value = int16( ...
  [-2000 -1000 0 1000 1500 2500 3000 4500 5000 5500 6500]);
table_Regen_contPL.Breakpoints(2).TunableSizeName = 'N2';
table_Regen_contPL.HasCoderInfo = false;
table_Regen_contPL.StructTypeInfo.Name = 'Regen_contPL';
table_Regen_contPL.StructTypeInfo.DataScope = 'Auto';
table_Regen_contPL.StructTypeInfo.HeaderFileName = '';

table_Xload_dur_ms = Simulink.LookupTable;
table_Xload_dur_ms.Table.DataType = 'uint16';
table_Xload_dur_ms.Table.Min = 0;
table_Xload_dur_ms.Table.Max = 3000;
table_Xload_dur_ms.Table.Unit = 'msec';
table_Xload_dur_ms.Table.FieldName = 'cal_table_vals_Xload_dur_ms';
table_Xload_dur_ms.Table.Description = '';
table_Xload_dur_ms.Table.Value = uint16( ...
  [3000; 3000; 2000; 1250; 500; 250; 125; 75; 50; 30; 10]);
table_Xload_dur_ms.BreakpointsSpecification = 'Explicit values';
table_Xload_dur_ms.SupportTunableSize = false;
table_Xload_dur_ms.Breakpoints.DataType = 'int16';
table_Xload_dur_ms.Breakpoints.Min = 0;
table_Xload_dur_ms.Breakpoints.Max = 1700;
table_Xload_dur_ms.Breakpoints.Unit = 'A';
table_Xload_dur_ms.Breakpoints.FieldName = ...
  'cal_table_bkpts_Xload_amps_A';
table_Xload_dur_ms.Breakpoints.Description = '';
table_Xload_dur_ms.Breakpoints.Value = uint16( ...
  [0; 180; 250; 325; 500; 700; 900; 1100; 1300; 1500; 1700]);
table_Xload_dur_ms.Breakpoints.TunableSizeName = 'N1';
table_Xload_dur_ms.HasCoderInfo = false;
table_Xload_dur_ms.StructTypeInfo.Name = 'Xload_dur_ms';
table_Xload_dur_ms.StructTypeInfo.DataScope = 'Auto';
table_Xload_dur_ms.StructTypeInfo.HeaderFileName = '';

